[package]
name = "tmux_launch"
version = "0.1.0"
authors = ["PowerSnail <hj@powersnail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
